
server:
  port: ${EUREKA_PORT:8001}

spring:
  application:
    name: kupproject-eureka

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/